/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    GithubIcon: typeof import('./components/icons/GithubIcon.vue')['default']
    MisskeyIcon: typeof import('./components/icons/MisskeyIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViteIcon: typeof import('./components/icons/MisskeyIcon.vue')['default']
    XIcon: typeof import('./components/icons/XIcon.vue')['default']
  }
}
